-- vanilla Config
require('ys.settings')
require('ys.keybinds')
require('ys.plugins-setup')
require("ys.plugins.dracula")
require("ys.plugins.tokyonight")
require('ys.colorscheme')

-- plugins
require('ys.plugins.comment')
require('ys.plugins.nvim-tree')
require('ys.plugins.lualine')
require('ys.plugins.telescope')
require('ys.plugins.nvim-cmp')
require('ys.plugins.lsp.mason')
require('ys.plugins.lsp.lspsaga')
require('ys.plugins.lsp.lspconfig')
require('ys.plugins.transparent')
require("ys.plugins.bufferline")
require("ys.plugins.gitsigns")
require("ys.plugins.gitsigns")
require("ys.plugins.autopairs")
require("ys.plugins.treesitter")
